- name: pull latest Psono Client image for update
  docker_image:
    source: pull
    force_source: yes
    name: "psono/psono-client:{{ psono_frontend_version_tag }}"
  tags: [never, update]

- name: Recreate Psono frontend container
  docker_container:
    recreate: yes
    name: "{{ psono_frontend_container_name }}"
    state: started
    image: "psono/psono-client:{{ psono_frontend_version_tag }}"
    volumes:
      - "{{ psono_frontend_config_path }}:/usr/share/nginx/html/config.json"
    restart_policy: "unless-stopped"
    detach: yes
    container_default_behavior: compatibility
    ports:
     - "127.0.0.1:{{ psono_frontend_local_port }}:80"
  tags: [never, update]

- name: Ensure Psono frontend container is present and started
  docker_container:
    name: "{{ psono_frontend_container_name }}"
    state: started
    image: "psono/psono-client:{{ psono_frontend_version_tag }}"
    volumes:
      - "{{ psono_frontend_config_path }}:/usr/share/nginx/html/config.json"
    restart_policy: "unless-stopped"
    detach: yes
    container_default_behavior: compatibility
    ports:
     - "127.0.0.1:{{ psono_frontend_local_port }}:80"