- name: pull latest Psono Admin Client image for update
  docker_image:
    source: pull
    force_source: yes
    name: "psono/psono-admin-client:{{ psono_admin_frontend_version_tag }}"
  tags: [never, update]

- name: Recreate Psono admin frontend container
  docker_container:
    recreate: yes
    name: "{{ psono_admin_frontend_container_name }}"
    state: started
    image: "psono/psono-admin-client:{{ psono_admin_frontend_version_tag }}"
    volumes:
      - "{{ psono_admin_frontend_config_path }}:/usr/share/nginx/html/config.json"
    restart_policy: "unless-stopped"
    detach: yes
    container_default_behavior: compatibility
    ports:
     - "127.0.0.1:{{ psono_admin_local_port }}:80"
  tags: [never, update]

- name: Ensure Psono admin frontend container is present and started
  docker_container:
    name: "{{ psono_admin_frontend_container_name }}"
    state: started
    image: "psono/psono-admin-client:{{ psono_admin_frontend_version_tag }}"
    volumes:
      - "{{ psono_admin_frontend_config_path }}:/usr/share/nginx/html/config.json"
    restart_policy: "unless-stopped"
    detach: yes
    container_default_behavior: compatibility
    ports:
     - "127.0.0.1:{{ psono_admin_local_port }}:80"