- name: Ensure FileServer data dir is present
  file:
    path: "{{ psono_fileserver_data_path }}"
    state: directory


- name: Generate fileserver conf script
  template:
    src: fileserver_config_script.sh.j2
    dest: "{{ psono_config_dir }}fileserver_config_script.sh"
    mode: 0700

- name: Generate fileserver on host if not exist using deployed script
  command: "/bin/bash {{ psono_config_dir }}fileserver_config_script.sh"
  args:
    creates: "{{ psono_fileserver_config_path }}"


