- name: Create Postgres for Psono
  become: yes
  hosts: psono_host
  vars_files:
    - secrets.yml
  roles:
  - postgres
  - psono_backend
  - psono_frontend
  - psono_admin_frontend
  - nginx_reverse_proxy
  - psono_fileserver
  - psono_backup