- name: Configure Psono
  include_tasks: config.yml

- name: Start Psono
  include_tasks: start.yml

- name: Enable auto Psono cleanup
  include_tasks: schedule_cleanup.yml

- name: Bootstrap Psono authentication
  include_tasks: bootstrap_auth.yml