- name: Install Nginx
  include_tasks: install.yml
  
- name: Configure and start nginx
  include_tasks: configure.yml

- name: Configure certbot certificate and renewal
  include_tasks: certbot.yml
  when: not psono_external_reverse_proxy