- name: Install Nginx
  include: install.yml
  
- name: Configure and start nginx
  include: configure.yml

- name: Configure certbot certificate and renewal
  include: certbot.yml
  when: not psono_external_reverse_proxy